### ISSUE TITLE
keyerror

### ISSUE THREAD

**Issue by swxhha** [magkai/CONQUER#11]
Hi,I'm having a hard time reproducing the code and would appreciate your help.Thanks a lot!

I set up a virtual environment strictly according to the readme. When I execute python rlMain.py configs/train_idealRef_noisyUser_config.json,I have the following problem:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\pydevd.py", line 1438, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2020.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/STUDY/CONQUER-master/main/rlMain.py", line 239, in <module>
    average_return = collect_episodes_with_rollouts(kgEnv, collect_policy,num_episodes, num_rollouts)
  File "C:/STUDY/CONQUER-master/main/rlMain.py", line 180, in collect_episodes_with_rollouts
    time_step = environment.reset()
  File "C:\Users\XMGO\anaconda3\envs\ENV_conquer\lib\site-packages\tf_agents\environments\py_environment.py", line 141, in reset
    self._current_time_step = self._reset()
  File "C:\STUDY\CONQUER-master\main\rlEnvironment.py", line 156, in _reset
    obs = self._get_observation()
  File "C:\STUDY\CONQUER-master\main\rlEnvironment.py", line 115, in _get_observation
    self.start_id = self.starts_per_question[self.qId][start_counter] 
KeyError: '1-0'

Then I found that under the data folder, the first value of questionId_list_trainset.json is "1-0", but there is no index "1-0" in reachable_startpoints_propagated_trainset.json, so a keyerror: '1-0' occurs. I found that there are many mismatched keys in the above two files. I'm wondering if I'm doing something wrong at some point and how to fix this.

**Comment by magkai** [comment]
Hi,

I checked the respective files. You are right that the question with id "1-0" (among others) is contained in the questionId_list_trainset.json but not in the reachable_startpoints_propagated_trainset.json. This is the case because the questionId list contains all question ids whereas it could be the case that we have not found context entities (startpoints) for each question. Therefore, not all qids are contained in the startpoints file. Relevant here is the question_start_indices_trainset.json file which is supposed to only take qids for which entities exist in the startpoints file so no key error should occur. I checked it and it is supposed to work correctly. Maybe you use another file here?

Best Regards,
Magdalena

**Comment by swxhha** [comment]
Hi,

Thank you very much for your willingness to reply me in your busy schedule!It helps me a lot.

You mean I can use **question_start_indices_trainset.json** instead of **questionId_list_trainset.json** for "question_list" input, right? 
I have a confusion here. Why are the data formats of the two files different? **questionId_list_trainset.json** is in string format, such as "1-0", "1-0-0", "1-0-1", "1-0-2" and so on. However **question_start_indices_trainset.json** is in array format like [0, 0], [2, 0], [2, 1], [6, 0], [6, 1], etc. Do these two files play the same role in the program? 

I have another confusion,.Do  **startPoints_trainset.json**,    **startpoints_propagated_trainset.json**，**reachable_startpoints_propagated_trainset.json**,  (and several other dictionary files with similar data formats)   all contain context entities (startpoints) information?  Why is **reachable_startpoints_propagated_trainset.json** selected as input for "starts_per_question" in the training configuration file in the main folder?

Looking forward to your reply.

Best Regards,
Fei

**Comment by swxhha** [comment]
Supplementary note, I encountered keyerror when using the following configuration：

    "checkpoint_path": "../data/checkpoints/main_exp/idealUser-idealRefPred",

    "starts_per_question": "../data/train_data/reachable_startpoints_propagated_trainset.json",
    "question_list": "../data/train_data/questionId_list_trainset.json",
    "paths": "../data/train_data/contextPaths_trainset.json",
    "answers": "../data/train_data/all_answers_trainset.json",
    "questions": "../data/train_data/all_questions_trainset.json",
    "action_nbrs": "../data/train_data/action_numbers_trainset.json",
    "next_questions": "../data/train_data/next_questions_trainset.json",
    "next_reformulations": "../data/train_data/next_reformulations_ideal_trainset.json",
    "q_start_indices": "../data/train_data/question_start_indices_trainset.json",

    "encoded_questions": "../data/train_data/encoded_questions_trainset.pickle",
    "encoded_actions": "../data/train_data/encoded_paths_trainset.pickle"

**Comment by magkai** [comment]
Hi,

no I didn't mean that you should replace questionId_list_trainset.json with question_start_indices_trainset.json. These two files serve different purposes: questionId_list contains ids in string format ("1-0", "456-3-2", etc.). Question_start_indices contains lists of indices (e.g. [1,2]), where the first entry in the list is used to access the respective entry in the questionId_list and the second one is used to access a respective entity in the startpoint file (please have a look at the code: rlEnvironment.py line 110 - 113).

Yes, startPoints_trainset.json, startpoints_propagated_trainset.json，reachable_startpoints_propagated_trainset.json, all contain entities. The reachable ones are the final ones, the others are intermediate files (feel free to try the others as well). For training, we want to use only startpoints for which the answer is in fact reachable in one hop, otherwise the agent cannot learn anything if all actions lead to wrong answers (therefore the reachable check). At inference time we don't have this information available (no reachable entities file).

I just executed the rlMain.py with the respective json config. I don't get a key error, so I am afraid it is hard for me to tell what could be the problem here for you.

Best Regards,
Magdalena

**Comment by swxhha** [comment]
Thank you very much！In the end I solved the problem and successfully ran the program.
