### ISSUE TITLE
The neo4j database

### ISSUE THREAD

**Issue by pranavajitnair** [magkai/CONQUER#2]
Hi,
For the property key 'rel' in the neo4j database, P stands for Wikidata property, but I couldn't quite understand what the number following '-' represents.  Also, I wanted to know the semantics for the 'rel' property key for the various relations types. 'rel' looked like the following for different relation types:
```
P1545-9|Q55128945_P50-9_Q60326768|P1932-0          qo_qo
P571-5713093_Q79146938|P1326-105964                o_qualifierobj
P1120-22160_+4934|P585-6816913                     s_qualifierobj
P8019-13|P2139-7765_+6                             s_o_qualifiers
P17-8544305                                        triples
```
Thanks

**Comment by magkai** [comment]
Hi,

thanks for your interest in our KG representation.
The number following "-" in relations is used to make the respective predicate unique. We just incremented this number whenever we saw the same predicate but in a different statement while traversing the Wikidata dump.

Qualifiers are used in Wikidata to give additional information to a main fact and they are crucial in answering many questions. In our work, agents walk over the KG to answers in its neighborhood. For our KG representation, we squeeze in the information from the qualifiers to the main fact and from the main fact to the qualifiers so that the agents do not miss any relevant information while following a path on the KG. Please also see our paper for more details: https://arxiv.org/abs/2105.04850.

For the examples you had:

* qo_qo (dump with paths between two qualifier objects):
`P1545-9` (*first qualifier predicate*) `|Q55128945` (*main fact subject*)`_P50-9` (*main fact predicate*) `_Q60326768` (*main fact object*)`|P1932-0` (*second qualifier object*) 
*  o_qualifierobj (dump with paths from main fact object to a qualifier object):
`P571-5713093` (*main fact predicate*) `_Q79146938` (*main fact subject*) `|P1326-105964` (*qualifier predicate*) 
*  s_qualifierobj (dump with paths from main fact subject to a qualifier object):
`P1120-22160` (*main fact predicate*) `_+4934` (*main fact object*) `|P585-6816913` (*qualifier predicate*)
* s_o_qualifiers (dump with paths from main fact subject to object augmented by its qualifier facts):
`P8019-13` (*main fact predicate*) `|P2139-7765` (*qualifier predicate*) `_+6` (qualifier object) 
* triples (dump with standard triples without qualifier information):
`P17-8544305` (*predicate*) 


Here is a sample fact with resolved entities and predicates:

```
AvengersEndgame, partOfSeries, MarvelCinematicUniverse (main fact)
AvengersEndgame, followedBy, SpiderManFarFromHome (qualifier 1)
AvengersEndgame, follows, CaptainMarvel (qualifier 2)
AvengersEndgame, seriesOrdinal, 22 (qualifier 3)
```

Some examples how the relations for this fact look like in our representation:

* Main fact relation as stored in s_o_qualifiers:
    ```
    partOfSeries|followedBy_SpiderManFarFromHome|follows_CaptainMarvel|seriesOrdinal_22
    ```
* Relation between `subject` and `qualifier 1` as stored in s_qualifierobj: 
    ```
    partOfSeries_MarvelCinematicUniverse|followedBy
    ```
* Relation between `object` and `qualifier 1` as stored in o_qualifierobj: 
    ```
    partOfSeries_AvengersEndgame|followedBy
    ```
* Relation between `qualifier 1` and `qualifier 2` as stored in qo_qo: 
    ```
    followedBy|AvengersEndgame_partOfSeries_MarvelCinematicUniverse|follows
    ```
I hope this answers your questions.

Best Regards,
Magdalena

**Comment by pranavajitnair** [comment]
Hi,
Thanks a lot for the explanation and the example. Yes, all my questions have been answered.

Regards
Pranav
