### ISSUE TITLE
Final metric calculation problems

### ISSUE THREAD

**Issue by 2213500360** [magkai/CONQUER#3]
Hi!
In your work , is it considered a wrong answer if the answer format is different from the golden answer ? For example, if the golden answer to a question is "10 minutes" and the answer on Wikidata is "+10," is that considered wrong? Because I can't find a part of your published code that deals with this kind of problem. Are the final metrics derived from the results in Wikidata without any processing?
Looking forward to your reply, thank you!

**Comment by magkai** [comment]
Hi,
thanks for your question. You can have a look at the utils class (https://github.com/magkai/CONQUER/blob/73d1ff0af2dc13af7329e52f7166d9edba25dc27/utils/utils.py). There, we convert timestamps from the wikidata format to human-readable forms. Also, in getLabel() some processing is performed (for example, "+" is split away). 
But you are right, there might be still some cases where the answer is actually correct but we cannot say since it does not directly match the gold answer. 

Best Regards,
Magdalena

**Comment by 2213500360** [comment]
Hi, 
thank you for your answer. In addition, I find that the results of your work applied to ConvQuestions (without reformulations) on the website https://convex.mpi-inf.mpg.de/ are P@1=0.240, MRR@5=0.279, This is different from the result P@1=0.263 and Hit@5=0.343 mentioned on page 8 of your paper. Why is this?

**Comment by magkai** [comment]
Hi, 
the results of our method on ConvQuestions reported in the paper are for all turns, while the ones on the ConvQuestions leaderboard (https://convex.mpi-inf.mpg.de/) are without the first turn for a fair comparison, since CONVEX was evaluated on turns > 1 only.

Best Regards,
Magdalena
