### ISSUE TITLE
meaning of collect_episodes_with_rollouts

### ISSUE THREAD

**Issue by lihuiliullh** [magkai/CONQUER#8]
May I know the meaning of the following code? Thx.

![image](https://user-images.githubusercontent.com/53407011/188047691-b68ce29e-1857-492e-8345-6a61c241885c.png)

**Comment by magkai** [comment]
Hi,

- we sample further actions from the probability distribution of the policy network (line 196-200)
- then get rewards for these actions from the environment (line 205-208)
- and store the additionally collected data in the replay buffer (209-211)

If we only sample one action, the update would be very sparse (since we can have up to 1000 possible actions to choose from). Therefore, we "try out" 20 actions and get feedback for them for better exploration.

Best Regards,
Magdalena

**Comment by lihuiliullh** [comment]
Thanks.
