### ISSUE TITLE
Why doesn't the model use the answers in the training data to decision reward?

### ISSUE THREAD

**Issue by lihuiliullh** [magkai/CONQUER#9]
I have a little question about the reward in this paper.
People usually think if the answer returned by the model is correct (answers exist in training data), then the reward is 1, otherwise the reward is -1.
But this paper uses reformulation prediction model to decide the reward. 
May I know whether reformulation prediction model can guarantee to return 1 if the answer returned by the model is correct?

![image](https://user-images.githubusercontent.com/53407011/188242754-5290528d-ad77-428e-acb2-e11ff2090827.png)

**Comment by magkai** [comment]
Hi,

this is exactly the goal of this paper: to **not** learn from gold labeled answers, but assume the more realistic setting that this information is not available. As a proxy, we assume that the user's reformulation behavior may tell us whether a previously returned system answer was correct or not. 
This assumption introduces some noise in our rewards, since the user may not always behave as expected (reformulate if the previous answer was wrong) and our reformulation predictor can make incorrect predictions. Please have a look at section 7.2 to see the different configurations which we use to explore the effect of this assumption. One configuration, the` IdealUser-IdealReformulationPredictor`, basically assumes a user behaving exactly as we expect and an predictor that does not make any mistakes. This configuration is equivalent to using the gold labeled answers.
We can see in the experiments that this introduced noise does not result in significant performance drop.

Best Regards,
Magdalena
